In [3]:
#!/usr/bin/env python3
# Download the 56 zip files in Images_png in batches
import urllib.request

# URLs for the zip files
links = [
    'https://nihcc.box.com/shared/static/vfk49d74nhbxq3nqjg0900w5nvkorp5c.gz',
    'https://nihcc.box.com/shared/static/i28rlmbvmfjbl8p2n3ril0pptcmcu9d1.gz',
    'https://nihcc.box.com/shared/static/f1t00wrtdk94satdfb9olcolqx20z2jp.gz',
	'https://nihcc.box.com/shared/static/0aowwzs5lhjrceb3qp67ahp0rd1l1etg.gz',
    'https://nihcc.box.com/shared/static/v5e3goj22zr6h8tzualxfsqlqaygfbsn.gz',
	'https://nihcc.box.com/shared/static/asi7ikud9jwnkrnkj99jnpfkjdes7l6l.gz',
	'https://nihcc.box.com/shared/static/jn1b4mw4n6lnh74ovmcjb8y48h8xj07n.gz',
    'https://nihcc.box.com/shared/static/tvpxmn7qyrgl0w8wfh9kqfjskv6nmm1j.gz',
	'https://nihcc.box.com/shared/static/upyy3ml7qdumlgk2rfcvlb9k6gvqq2pj.gz',
	'https://nihcc.box.com/shared/static/l6nilvfa9cg3s28tqv1qc1olm3gnz54p.gz',
	'https://nihcc.box.com/shared/static/hhq8fkdgvcari67vfhs7ppg2w6ni4jze.gz',
	'https://nihcc.box.com/shared/static/ioqwiy20ihqwyr8pf4c24eazhh281pbu.gz'
]

for idx, link in enumerate(links):
    fn = '../data/nihcc_chest_xray/images_%02d.tar.gz' % (idx+1)
    print('downloading'+fn+'...')
    urllib.request.urlretrieve(link, fn)  # download the zip file

print("Download complete. Please check the checksums")



downloading../data/nihcc_chest_xray/images_01.tar.gz...
downloading../data/nihcc_chest_xray/images_02.tar.gz...
downloading../data/nihcc_chest_xray/images_03.tar.gz...
downloading../data/nihcc_chest_xray/images_04.tar.gz...
downloading../data/nihcc_chest_xray/images_05.tar.gz...
downloading../data/nihcc_chest_xray/images_06.tar.gz...
downloading../data/nihcc_chest_xray/images_07.tar.gz...
downloading../data/nihcc_chest_xray/images_08.tar.gz...
downloading../data/nihcc_chest_xray/images_09.tar.gz...
downloading../data/nihcc_chest_xray/images_10.tar.gz...
downloading../data/nihcc_chest_xray/images_11.tar.gz...
downloading../data/nihcc_chest_xray/images_12.tar.gz...
Download complete. Please check the checksums


In [22]:
import numpy as np
from scipy.special import softmax

In [94]:
a = np.array([[-1.45175124,  2.54659562, -1.57316403]])
a = np.array([[-0.63483063,  0.73849625, -0.19395639]])
a = np.array([[-1.58292796,  0.29200524,  0.86723179]])


In [84]:
x = np.array([[1, 0.5, 0.2, 3],
[1,  -1,   7, 3],
[2,  12,  13, 3]
])

In [93]:
sx = softmax(x, axis=1)
print(sx)
np.sum(sx[0])

[[1.05877070e-01 6.42176889e-02 4.75736340e-02 7.82331607e-01]
 [2.42746030e-03 3.28521027e-04 9.79307378e-01 1.79366403e-02]
 [1.22093673e-05 2.68929212e-01 7.31025390e-01 3.31885014e-05]]


1.0

In [89]:
np.sum(sx, axis=1)

array([1., 1., 1.])

In [95]:
s = softmax(a, axis=1)
s

array([[0.05232703, 0.34119231, 0.60648066]])

In [25]:
epsilon = 0.0000001
def predictive_entropy(prob):
    return -1 * np.sum(np.log(prob+epsilon) * (prob)) # entropy of class distribution

In [98]:
for __ in s[0]:
    print(__*np.log(__+epsilon))

-0.15437731502601945
-0.3668870624404453
-0.3032902293880359


In [48]:
a = [[4.89804053e-05, 3.42872717e-04, 5.91209555e-05]]
a =  [[1.72548332e-05, 9.40525873e-04, 1.52820586e-05]]
for __ in a[0]:
    print(__*np.log(__+epsilon))


-0.00018914126151198355
-0.006554491967580408
-0.00016936049179716868


In [112]:
s = [[0.04, 0.01, 0.95],
     [0.09,0.90,0.01]]
np.apply_along_axis(predictive_entropy, axis=1, arr=s)


array([0.22353506, 0.35759097])

In [116]:
np.argmax(s, axis=1)

array([2, 1], dtype=int64)

In [31]:
predictive_entropy(a)

0.0210685931633116